### ISSUE TITLE
Basic/0xFF01 attribute results in garbage string.

### ISSUE THREAD

**Issue by Frans-Willem** [Frans-Willem/AqaraHub#10]
Maybe for certain attributes force a specific attribute type or decoding method ?

**Comment by Frans-Willem** [comment]
First attempt:
https://github.com/Frans-Willem/AqaraHub/commit/7169c43675409054ecb06f47ab7a833e885d3bdc
https://github.com/Frans-Willem/AqaraHub/commit/a98a3eaca962d41d545c59729a2163433bbda0ca

Temperature sensor:
```
AqaraHub/report/158D0001A2B6A0/1/Basic/0xFF01 {"type":"xiaomi_ff01","value":{"1":{"type":"uint16","value":2975},"10":{"type":"uint16","value":8058},"100":{"type":"int16","value":2048},"101":{"type":"uint16","value":8144},"4":{"type":"uint16","value":424},"5":{"type":"uint16","value":15},"6":{"type":"uint40","value":1}}}
```

Smart plug:
```
AqaraHub/report/158D00015D231D/1/Basic/0xFF01 {"type":"xiaomi_ff01","value":{"100":{"type":"bool","value":false},"149":{"type":"single","value":0.05700818449258804},"150":{"type":"uint32","value":2310},"152":{"type":"single","value":0.0},"154":{"type":"uint8","value":16},"3":{"type":"int8","value":25},"5":{"type":"uint16","value":6},"7":{"type":"uint64","value":0},"8":{"type":"uint16","value":4884},"9":{"type":"uint16","value":256}}}
```

These are the only ones I own that report the FF01 attribute. I'm not entirely convinced this is the proper way to decode it, so I'll leave it open for a while and see if anyone knows any more about the encoding...

**Comment by Gabor9** [comment]
Looks good to me!

lumi.weather:

`AqaraHub/report/158D0001715BEE/1/Basic/0xFF01: {"type":"xiaomi_ff01","value":{"1":{"type":"uint16","value":3025},"10":{"type":"uint16","value":64989},"100":{"type":"int16","value":1897},"101":{"type":"uint16","value":4980},"102":{"type":"int32","value":99978},"4":{"type":"uint16","value":17320},"5":{"type":"uint16","value":12},"6":{"type":"uint40","value":458753}}}`

lumi.sensor_magnet.aq2:

`Publishing to AqaraHub/report/158D0001B14707/1/Basic/0xFF01: {"type":"xiaomi_ff01","value":{"1":{"type":"uint16","value":2995},"10":"type":"uint16","value":0},"100":{"type":"bool","value":false},"3":{"type":"int8","value":30},"4":{"type":"uint16","value":17320},"5":{"type":"uint16","value":61},"6":{"type":"uint40","value":2}}}`

**Comment by Frans-Willem** [comment]
We should probably document the properties in this attribute at some point :/
For now, I'll close the issue :)
