### ISSUE TITLE
Smoke sensor attributes are not decoded properly.

### ISSUE THREAD

**Issue by Frans-Willem** [Frans-Willem/AqaraHub#16]
See https://github.com/Frans-Willem/AqaraHub/blob/master/documentation/devices/lumi.sensor_smoke.md

**Comment by Frans-Willem** [comment]
(I've ordered a smoke sensor myself, which should arrive in the coming weeks, I'll work on this once it arrives.)

**Comment by Gabor9** [comment]
Receive the same error for water sensor (lumi.sensor_wleak):

`<DEBG> [FRAME] << AREQ AF_INCOMING_MSG 00 00 00 00 4d dc 01 01 00 71 00 1d f9 18 00 00 43 1c 5f 11 3c 0a 05 00 42 15 6c 75 6d 69 2e 73 65 6e 73 6f 72 5f 77 6c 65 61 6b 2e 61 71 31 01 ff 42 22 01 21 db 0b 03 28 17 04 21 a8 43 05 21 5b 00 06 24 00 00 00 00 00 08 21 04 02 0a 21 00 00 64 10 00 4d dc 1d
<WARN> [ZclEndpoint] Exception on incoming message: Not enough data to decode integer
<DEBG> [FRAME] << AREQ AF_INCOMING_MSG 00 00 00 00 4d dc 01 01 00 83 00 bd f2 19 00 00 43 1c 5f 11 3d 0a 05 00 42 15 6c 75 6d 69 2e 73 65 6e 73 6f 72 5f 77 6c 65 61 6b 2e 61 71 31 01 ff 42 22 01 21 db 0b 03 28 18 04 21 a8 43 05 21 5b 00 06 24 00 00 00 00 00 08 21 04 02 0a 21 00 00 64 10 00 4d dc 1d
<WARN> [ZclEndpoint] Exception on incoming message: Not enough data to decode integer
`

**Comment by Frans-Willem** [comment]
Should be fixed by https://github.com/Frans-Willem/AqaraHub/commit/a2cc15fad172ccb9a323f30ea50991e6001c32d0
