### ISSUE TITLE
Cross compilation for Raspberry Pi / Raspbian

### ISSUE THREAD

**Issue by Frans-Willem** [Frans-Willem/AqaraHub#22]
By some reports compiling on a raspberry pi takes almost an hour, and requires a 1G swap file.
We should look into cross compilation. Targetting Raspbian for RPi 1 and 2/3 would probably be helpful to a lot of users.

**Comment by Gabor9** [comment]
Just built a new compilation on RPi 3B and took 12 minutes with 1GB swap.

**Comment by voltagex** [comment]
I'm having a lot of trouble cross compiling - mainly due to boost - I end up not being able to link to `ontop_fcontext` inside of `libboost_context`, but I'm not sure it's right to post it as an issue here. @Frans-Willem, what would you prefer?

**Comment by voltagex** [comment]
No matter what configuration I use, on ARM I can't link to `ontop_fcontext`. If I could get a minimal test case I could report it to the boost project, but it's deep in C++ land and I don't understand it at all.

Current progress: https://github.com/baxterworks-build/Dockerfiles/tree/master/docker-aqarahub

References: https://stackoverflow.com/questions/41413791/unable-to-link-against-boost-libraries

**Comment by Frans-Willem** [comment]
Great job on the cross compilation docker! If you make a pull request with it added to this repo, I'll surely approve it :)

At some point I'd prefer to have something that pulls in the .deb packages for Boost and other libraries, links against that, and spits out a functional .deb for AqaraHub, but until that time comes, this is a near perfect substitute. Thanks again!

**Comment by voltagex** [comment]
Wow, I didn't realise this was a month ago. I am not happy with the current solution as it's messy and hartdcodes paths, but until I understand CMake more, it's the best I can do. Moving to a recent Ubuntu image and using the slightly older compilers there would help make this more "standard"

**Comment by voltagex** [comment]
Raised #51

**Comment by Frans-Willem** [comment]
Merged! Thanks for taking the effort to figure this out :)!
