### ISSUE TITLE
Smoke sensor and water leak sensor send unhandled commands

### ISSUE THREAD

**Issue by Frans-Willem** [Frans-Willem/AqaraHub#24]
Both these devices appear to be sending something that's not a ReportAttributes command. Both are on my way from China, and I'll attempt to debug them and get them working as soon as I receive them.

**Comment by mclei-asw** [comment]
Water leak sensor log:

Jun 15 20:09:17 mqtt2 env[721]: <DEBG> [FRAME] << AREQ AF_INCOMING_MSG 00 00 00 00 70 0b 01 01 00 34 00 1c ca a3 00 00 43 1c 5f 11 90 0a 05 00 42 15 6c 75 6d 69 2e 73 65 6e 73 6f 72 5f 77 6c 65 61 6b 2e 61 71 31 01 ff 42 22 01 21 db 0b 03 28 23 04 21 a8 43 05 21 12 00 06 24 00 00 00 00 00 08 21 04 02 0a 21 00 00 64 10 00 70 0b 1d
Jun 15 20:09:17 mqtt2 env[721]: <WARN> [ZclEndpoint] Exception on incoming message: Not enough data to decode integer
Jun 15 20:09:17 mqtt2 env[721]: <DEBG> [FRAME] >> SREQ UTIL_ADDRMGR_NWK_ADDR_LOOKUP 70 0b
Jun 15 20:09:17 mqtt2 env[721]: <DEBG> [FRAME] << SRSP UTIL_ADDRMGR_NWK_ADDR_LOOKUP e6 06 2f 02 00 8d 15 00
Jun 15 20:09:26 mqtt2 env[721]: <DEBG> [FRAME] << AREQ AF_INCOMING_MSG 00 00 00 05 70 0b 01 01 00 00 00 82 3c a4 00 00 09 19 91 00 01 00 00 ff 00 00 70 0b 1d
Jun 15 20:09:26 mqtt2 env[721]: <DEBG> [ZclEndpoint] ZCL Frame not handled Local 0
Jun 15 20:09:26 mqtt2 env[721]: <DEBG> [FRAME] >> SREQ UTIL_ADDRMGR_NWK_ADDR_LOOKUP 70 0b
Jun 15 20:09:26 mqtt2 env[721]: <DEBG> [FRAME] << SRSP UTIL_ADDRMGR_NWK_ADDR_LOOKUP e6 06 2f 02 00 8d 15 00

Jun 15 20:10:09 mqtt2 env[721]: <DEBG> [FRAME] << AREQ AF_INCOMING_MSG 00 00 00 05 70 0b 01 01 00 05 00 da 44 a6 00 00 09 19 92 00 00 00 00 ff 00 00 70 0b 1d
Jun 15 20:10:09 mqtt2 env[721]: <DEBG> [ZclEndpoint] ZCL Frame not handled Local 0
Jun 15 20:10:09 mqtt2 env[721]: <DEBG> [FRAME] >> SREQ UTIL_ADDRMGR_NWK_ADDR_LOOKUP 70 0b
Jun 15 20:10:09 mqtt2 env[721]: <DEBG> [FRAME] << SRSP UTIL_ADDRMGR_NWK_ADDR_LOOKUP e6 06 2f 02 00 8d 15 00

**Comment by Frans-Willem** [comment]
I've taken a more in-depth look at this, and it appears I've made a bit of a mistake when deciding on MQTT topic names. I assumed devices would pretty much always send attribute reports, and from the hub side you'd always send commands. Turns out, in this case, the devices send commands to the hub too. Technically I know what to do, but I'm in a bit of an analysis-paralysis on how to implement things properly. I've tried to describe the choices to be taken below. Any feedback would be highly appreciated.

First of all it's not possible to mqtt publish received commands to the same topic that AqaraHub is subscribing to for sending commands (MQTT doesn't really support "publish this to anyone but myself", and for other listeners it would be impossible to differentiate between a command that another client sent to the zigbee network or a command that came from the zigbee network).
I think the best solution to that problem is to publish everything coming *from* the Zigbee network to something like ```AqaraHub/in/...```, and anything that should be sent out to the zigbee network to something like ```AqaraHub/out/...```.

Then there's the fact that there are global commands (Report attributes, Read attributes, Write attributes) that are implemented on all clusters, and there are cluster-local commands like IAS Zone/Zone Status Changed.
This would mandate something like
```AqaraHub/in-or-out/device-id/endpoint-id/cluster-name/global-or-local/command-name```, with some examples:

```AqaraHub/in/158D0001DC9587/1/OnOff/global/Report Attributes``` upon receiving on-off attributes
```AqaraHub/in/158D0001DC9587/1/IAS Zone/local/Zone Status Changed``` upon the water alarm triggering
```AqaraHub/out/158D0001DC9587/1/OnOff/local/Toggle``` to toggle a light.

The remaining problem is then that ideally we'd like to have seperate topics for seperate attributes, whereas the "Report Attributes" command may contain several within the same cluster. I think for this purposes I could add an exception where in this case an array of attribute changes is published to the ```.../Report Attributes``` topic, but each item in that array is also published to (for example) ```OnOff/global/Report Attributes/OnOff```.

I suspect a topic scheme like that would cover most, hopefully all, bases, but it's quite verbose and long. Does anyone see room for improvement before I go and mess up everyone's MQTT topics again :p?

**Comment by mclei-asw** [comment]
I am not familiar with the topic structure you are describing, but:
- I am still in testing phase, so changing the topic scheme does not break anything to me
- I really want to have each attribute in separate topic (and I would also prefer some configuration switch to use just plain values and not JSONs)
- I would like for example separate attribute for battery status (or something simpler identified in report structure)

**Comment by Frans-Willem** [comment]
Alright, one thing I figured about the new topic scheme, is that the whole "local" vs "global" thing doesn't need to be in the topic. There is no overlap between local command names and global command names, so I can easily distinguish from either one by just the command name.

Furthermore I think the in/out part should be further down the topic-name-tree. Device and endpoint ID are definitely higher in grouping order.

The previous examples may look like:

```AqaraHub/158D0001DC9587/1/OnOff/in/Report Attributes``` upon receiving on-off attributes
```AqaraHub/158D0001DC9587/1/IAS Zone/in/Zone Status Changed``` upon the water alarm triggering
```AqaraHub/158D0001DC9587/1/OnOff/out/Toggle``` to toggle a light.

or possibly:

```AqaraHub/158D0001DC9587/1/in/OnOff/Report Attributes``` upon receiving on-off attributes
```AqaraHub/158D0001DC9587/1/in/IAS Zone/Zone Status Changed``` upon the water alarm triggering
```AqaraHub/158D0001DC9587/1/out/OnOff/Toggle``` to toggle a light.

(I think I might prefer the latter, as I feel the cluster-name and command-name should be close together).

Having attributes in seperate topic is something that I heavily agree with, which is why I think I'll definitely add sub-topics for "Report Attributes". Example:

```AqaraHub/158D0001DC9587/1/in/OnOff/Report Attributes``` would received ```[{'attribute':'State', value:' true}, {'attribute':'PowerUsed', 'value':1234}]```
```AqaraHub/158D0001DC9587/1/in/OnOff/Report Attributes/State``` would received ```true```
```AqaraHub/158D0001DC9587/1/in/OnOff/Report Attributes/PowerUsed``` would received ```1234```

About the choice between of plain values instead of JSON, I've considered it in the past, but decided against it for symmetry. e.g. when receiving a value from Zigbee, it's obviously easy to just serialize it as the plain value, but then when trying to send something from MQTT to Zigbee ```1``` could be interpreted as a uint8, int8, uint16, uint24, ..., single, float, double, and there's really no way to know which one the zigbee device will support.

I know that OpenHAB supports javascript (and thus JSON) transforms, and Domoticz needs some kind of translation like Node-Red inbetween anyway that can tackle the JSON stuff, which is why I figured it wouldn't be a very big problem. May I ask what kind of home automation setup you'd like to run that wouldn't support JSON?

Finally about the battery status on Xiaomi devices: I don't intend to parse that any further in the near future than I've done so far. I've already added a lot of code just for that one attribute (both to handle malformed packets, as well as destructure it to what it is now), and I don't think all parts of it have been documented...

(If you'd like to discuss more about the plain-value vs JSON points, or the Xiaomi specific attributes, I'm definitely open to it, but I think it's better to open seperate issues at this point.)

**Comment by Frans-Willem** [comment]
Just wanted to give a heads-up that I'm still working on this. You can keep tabs on my progress in [this branch](https://github.com/Frans-Willem/AqaraHub/tree/feature/received-commands) ;).
In the current pace, I expected to finish this either next weekend or possibly the weekend after.

**Comment by Frans-Willem** [comment]
I think it's ready for testing, could you give it a spin ? It's all in [this branch](https://github.com/Frans-Willem/AqaraHub/tree/feature/received-commands).

I tested my water-leak sensor, and it's reporting the following:
```
<INFO> [PublishValue] Publishing to 'AqaraHub/00158d0001bb8d6d/1/in/IAS Zone/Zone Status Change Notification': {"Delay":0,"Extended Status":[false,false,false,false,false,false,false,false],"Zone ID":255,"Zone Status":[true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]}
```

The button is reporting like so:
```
<INFO> [PublishValue] Publishing to 'AqaraHub/00158d000152d7b2/1/in/OnOff/Report Attributes': {"reports":[{"Attribute data":{"type":"bool","value":true},"Attribute identifier":"OnOff"}]}
<INFO> [OnZclCommand] Looks like something per-attribute. Publishing per-attribute too
<INFO> [PublishValue] Publishing to 'AqaraHub/00158d000152d7b2/1/in/OnOff/Report Attributes/OnOff': {"type":"bool","value":true}
```

Examples of sending commands where the commands is encoded in the MQTT topic:
```
AqaraHub/00158d000152d7b2/1/out/OnOff/On: {}
AqaraHub/00158d000152d7b2/1/out/OnOff/Toggle: {}
AqaraHub/00158d000152d7b2/1/out/Window Covering/Go To Lift Percentage: {"Percentage Lift Value": 50}
```
(If a command has no payload, it's also possible to send an empty message.)
Or where the commands are encoded in the payload:
```
AqaraHub/00158d000152d7b2/1/out/OnOff: {"command": "On", "arguments": {}}
AqaraHub/00158d000152d7b2/1/out/OnOff: {"command": "Toggle"}
AqaraHub/00158d000152d7b2/1/out/Window Covering: {"command": "Go To Lift Percentage", "arguments": {"Percentage Lift Value": 50}}
```

Let me know if everything works for you too, so I can get to updating documentation and merging this :)

**Comment by mclei-asw** [comment]
First I was not able to compile it with errors like:

```
/home/pi/AqaraHub/src/znp/encoding.h:315:9: error: ‘isnan’ is not a member of ‘std’
     if (std::isnan(value)) {
         ^~~
/home/pi/AqaraHub/src/znp/encoding.h:320:16: error: ‘isinf’ is not a member of ‘std’
     } else if (std::isinf(value)) {
                ^~~
```
but after fixing it by:
```
diff --git a/src/znp/encoding.h b/src/znp/encoding.h
index ea33e9b..84b32db 100644
--- a/src/znp/encoding.h
+++ b/src/znp/encoding.h
@@ -6,6 +6,7 @@
 #include <tuple>
 #include <type_traits>
 #include "znp/znp.h"
+#include <cmath>
 
 namespace znp {
 typedef std::vector<uint8_t> EncodeTarget;

```
it works now.

I have tested both smoke sensor and water leak sensor.

**Comment by Frans-Willem** [comment]
Thanks! Would you like to make a pull request so those changes will be registered to you, or should I just commit it :)?

**Comment by mclei-asw** [comment]
If it is right solution, just commit it.

**Comment by Frans-Willem** [comment]
Merged to master, hurrah! :D
