### ISSUE TITLE
Run on Mac/Windows?

### ISSUE THREAD

**Issue by dzungpv** [Frans-Willem/AqaraHub#29]
It is possible to run this on Mac/Windows?

**Comment by Frans-Willem** [comment]
I haven't tested it. But Boost.Asio, what we're using to communicate over serial and MQTT, supports it, so I suspect it will compile fine :+1:.
Let me know if there's any specific compilation errors that I should look at :)

**Comment by Makave1i** [comment]
error on macos:
```/AqaraHub/src/zcl/zcl.h:442:10: error: class 'to_json_helper' was previously declared as a struct
      [-Werror,-Wmismatched-tags]
  friend class zcl::to_json_helper<zcl::ZclVariant>;
         ^
/AqaraHub/src/zcl/zcl.h:397:8: note: previous use is here
struct to_json_helper;
       ^
1 error generated.
make[2]: *** [CMakeFiles/common.dir/src/clusterdb/cluster_db.cpp.o] Error 1
make[1]: *** [CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2```

**Comment by speqtr** [comment]
I was able to successfully compile and run this project on macOS after making a couple of small changes: https://github.com/Frans-Willem/AqaraHub/pull/42

**Comment by Frans-Willem** [comment]
Just a heads up that @speqtr's branch was merged, so everything should work on Mac.

Has anyone attempted Windows yet ?

**Comment by phaethon** [comment]
I just attempted to compile this on FreeBSD and got similar error as reported under #42. 
FreeBSD 12.0
clang 6.0.1
GNU make 4.2.1
Boost libs 1.71

Beginning of the output (a lot of errors follow):
[  3%] Building CXX object CMakeFiles/common.dir/src/asio_executor.cpp.o
[  7%] Building CXX object CMakeFiles/common.dir/src/clusterdb/cluster_db.cpp.o
[ 11%] Building CXX object CMakeFiles/common.dir/src/coro.cpp.o
[ 14%] Building CXX object CMakeFiles/common.dir/src/dynamic_encoding/common.cpp.o
[ 18%] Building CXX object CMakeFiles/common.dir/src/dynamic_encoding/decoding.cpp.o
[ 22%] Building CXX object CMakeFiles/common.dir/src/dynamic_encoding/encoding.cpp.o
[ 25%] Building CXX object CMakeFiles/common.dir/src/logging.cpp.o
[ 29%] Building CXX object CMakeFiles/common.dir/src/mqtt_wrapper.cpp.o
[ 33%] Building CXX object CMakeFiles/common.dir/src/uri_parser.cpp.o
[ 37%] Building CXX object CMakeFiles/common.dir/src/zcl/encoding.cpp.o
In file included from ~/AqaraHub/src/zcl/encoding.cpp:1:
In file included from ~AqaraHub/src/template_lookup.h:3:
In file included from /usr/include/c++/v1/map:442:
In file included from /usr/include/c++/v1/__tree:16:
/usr/include/c++/v1/memory:2285:5: error: delete called on 'zcl::(anonymous namespace)::VariantEncodeHelper' that is abstract but has non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
    delete __ptr;
    ^
/usr/include/c++/v1/memory:2598:7: note: in instantiation of member function 'std::__1::default_delete<zcl::(anonymous namespace)::VariantEncodeHelper>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/usr/include/c++/v1/memory:2552:19: note: in instantiation of member function 'std::__1::unique_ptr<zcl::(anonymous namespace)::VariantEncodeHelper, std::__1::default_delete<zcl::(anonymous
      namespace)::VariantEncodeHelper> >::reset' requested here
  ~unique_ptr() { reset(); }
                  ^
/usr/include/c++/v1/utility:312:29: note: in instantiation of member function 'std::__1::unique_ptr<zcl::(anonymous namespace)::VariantEncodeHelper, std::__1::default_delete<zcl::(anonymous
      namespace)::VariantEncodeHelper> >::~unique_ptr' requested here
struct _LIBCPP_TEMPLATE_VIS pair
...

**Comment by phaethon** [comment]
This was the answer: https://stackoverflow.com/questions/10024796/c-virtual-functions-but-no-virtual-destructors
If you need I can make a proper PR. This is the diff that let me successfully compile.

index 7c425e8..ce710bb 100644
--- a/src/zcl/encoding.cpp
+++ b/src/zcl/encoding.cpp
@@ -16,6 +16,7 @@ struct VariantEncodeHelper {
   virtual void Decode(zcl::ZclVariant& variant,
                       znp::EncodeTarget::const_iterator& begin,
                       znp::EncodeTarget::const_iterator end) = 0;
+       virtual ~VariantEncodeHelper() = default;
 };
 
 // Implementation, templated, with some default error messages.
diff --git a/tests/template_lookup.cpp b/tests/template_lookup.cpp
index 9973923..40db1ba 100644
--- a/tests/template_lookup.cpp
+++ b/tests/template_lookup.cpp
@@ -9,6 +9,7 @@ enum class Numbers { One, Two, Three };
 class IHandler {
  public:
   virtual int GetNumber() = 0;
+       virtual ~IHandler() = default;
 };
 
 template <Numbers N>
@@ -17,23 +18,27 @@ class CHandler : public IHandler {
   virtual int GetNumber() override {
     throw std::runtime_error("Number not implemented");
   }
+       virtual ~CHandler() = default;
 };
 
 template <>
 class CHandler<Numbers::One> : public IHandler {
  public:
   virtual int GetNumber() override { return 1; }
+       virtual ~CHandler() = default;
 };
 
 template <>
 class CHandler<Numbers::Two> : public IHandler {
  public:
   virtual int GetNumber() override { return 2; }
+       virtual ~CHandler() = default;
 };
 template <>
 class CHandler<Numbers::Three> : public IHandler {
  public:
   virtual int GetNumber() override { return 3; }
+       virtual ~CHandler() = default;
 };
 
 struct HandlerFactory {

**Comment by Frans-Willem** [comment]
Applied your changes, thank you!

**Comment by Frans-Willem** [comment]
@all-contributors please add @phaethon for code
