### ISSUE TITLE
Report attributes values as JSON

### ISSUE THREAD

**Issue by Frans-Willem** [Frans-Willem/AqaraHub#3]
Reporting of attributes should be available as untyped, e.g.:
```json
123
true
"Hello world"
[123,true,"Hello world"]
```

As well as typed, e.g.:
```json
{"type":"uint8", "value": 123}
{"type":"bool", "value": true}
{"type":"octstr", "value":"Hello world"}
{"type":"struct", "value": [{"type":"uint8","value":123},{"type":"bool", "value":true},{"type":"octstr","value":"Hello world"}]}
```

(In the future, writing of attributes should be supported as typed. Untyped is more difficult, as we won't know what Zigbee type the attribute should be.)

**Comment by Frans-Willem** [comment]
Untyped is not yet posted to MQTT, but I'm not convinced it should be. to_json code supports it in case it's needed later.

**Comment by mclei-asw** [comment]
I would like to have untyped values in MQTT as I am interfacing it with other systems and parsing JSON is a big unnecessary overhead there, for example in Arduino.

Or have it configurable.

As I understand you have to know what device sends what values as you decode it to names like "Temperature Measurement/MeasuredValue". So I hope you are also able to "convert" the values to real number. For example temperature is reported as {"type":"int16","value":2581}, but I would like to see value "25.81".
