### ISSUE TITLE
Awesome project - Maybe join forces

### ISSUE THREAD

**Issue by ciotlosm** [Frans-Willem/AqaraHub#30]
Great work! I was looking at using this project as base for a gateway replacement and to avoid extra round trips over wifi from the xiaomi gateway. 

After going through many projects and clones and forks I was able to identify another project that had a bit more progress in terms of device support and documentation here: https://github.com/Koenkk/zigbee2mqtt

The guys there are really opened and there are a lot of people testing things. As you mentioned you got inspiration from `zigbee-shepherd` so I thought it would be great if we could also have you onboard. There are all sorts of bugs and quirks that your knowledge could help with. 

Even if you don't end up joining, the project there could help you with information around adding more device support (that part was extracted in it's own library): https://github.com/Koenkk/zigbee-shepherd-converters

Another benefit of the project is that it go support for integrating into Home Assistant as an addon: https://github.com/danielwelch/hassio-zigbee2mqtt

Thanks again!

**Comment by Frans-Willem** [comment]
Hey ciotlosm,

Thanks for the offer, but I'm not very fond of big projects in dynamic languages. In fact, if I were to write something like AqaraHub again I'd probably choose an even more strongly typed language like Rust or Haskell.

Let me know if you have any Zigbee specific questions, or if there's anything missing from AqaraHub that you'd like me to fix :)

Frans-Willem
