### ISSUE TITLE
domoticz integration

### ISSUE THREAD

**Issue by zoral566** [Frans-Willem/AqaraHub#32]
Sorry for the question, but how can I integrate it with domoticz? The device works, I paired some devices: 
00 20 59 c8 16 1d
<DEBG> [Report] Attempting to look up full source address for 5832
<DEBG> [FRAME] >> SREQ UTIL_ADDRMGR_NWK_ADDR_LOOKUP c8 16
<DEBG> [FRAME] >> SREQ UTIL_ADDRMGR_NWK_ADDR_LOOKUP c8 16
<DEBG> [FRAME] << SRSP UTIL_ADDRMGR_NWK_ADDR_LOOKUP 60 4f 9f 01 00 8d 15 00
<DEBG> [Report] Publishing to domoticz/in/report/00158D00019F4F60/1/Basic/0xFF02: {"type":"struct","value":[{"type":"bool","value":false},{"type":"uint16","value":3025},{"type":"uint16","value":5032},{"type":"uint40","value":1},{"type":"uint16","value":101},{"type":"uint8","value":89}]}
<DEBG> [Report] All done
Domoticz I created a mqtt client gateway with lan interface. What's next? How do you find the paired tools in domoticz?

**Comment by Frans-Willem** [comment]
Hey,

Domoticz expects it's MQTT input to be formatted in a very specific way, that doesn't match AqaraHub's output. I think your best bet would be to re-set AqaraHub to it's own topic, and then use Node-RED to do the translation.
There's quite a lot of documentation here: https://www.domoticz.com/wiki/MQTT

Which device are you trying to get working ? Might be able to give you a hint on what message to listen for, how to translate it, and how to forward it to Domoticz...

**Comment by zoral566** [comment]
Thank you for your reply. Unfortunately, this is beyond my ability. :) I used a door sensor and a motion detector at the moment. How should I use this tool (homeassistant or other)? It's not important for domoticz if there is a simpler solution.
