### ISSUE TITLE
MQTT server reconnection is missing

### ISSUE THREAD

**Issue by mclei-asw** [Frans-Willem/AqaraHub#33]
When AqaraHub application is started before MQTT server, the connection fails and no messages are delivered even there are messages like this one in log:

Jun 19 16:56:22 mqtt2 env[1981]: <DEBG> [Report] Publishing to AqaraHub/report/00158D0002132F39/1/OnOff/OnOff: {"type":"bool","value":false}

Also when started correctly and MQTT server is restarted, AqaraHub never reconnects again.

**Comment by Frans-Willem** [comment]
Is it OK if AqaraHub were to just exit if it loses (or fails) the MQTT connection, and expect SystemD to restart it ?

**Comment by mclei-asw** [comment]
As a temporary solution yes, but as final really no. I wanted to use this project in real smarthome.

**Comment by Frans-Willem** [comment]
Alright, I've changed the mqtt client to automatically reconnect 5 seconds after an error. I havne't been able to test it thoroughly at this point, could you check if this branch solves your problems?
https://github.com/Frans-Willem/AqaraHub/tree/feature/mqtt-reconnect

**Comment by mclei-asw** [comment]
It works for the initialization process. It repeats the connect till connected - OK
But it does not work when the connection is lost while already connected - it does not detect the connection lost at all - FAILED

**Comment by Frans-Willem** [comment]
Bummer! Thanks for testing, I'll give it another shot tomorrow :)

**Comment by Frans-Willem** [comment]
There's a new commit on that branch that should keep reconnecting in all cases. Apparently the MQTT library has two different handlers for either errors or "normal" disconnections, and I wasn't listening to the latter.

Could you confirm if this does indeed fix your problems, so I can merge it into master ?

**Comment by mclei-asw** [comment]
Great, it works. Tested both the startup without MQTT broker running and also restart of MQTT broker.

**Comment by Frans-Willem** [comment]
Thanks for testing! merged it to master just now.
I'll try to put in a few hours this and next week to get the water & smoke sensors working :)
