### ISSUE TITLE
Openwrt

### ISSUE THREAD

**Issue by utya1988** [Frans-Willem/AqaraHub#40]
Maybe somebody port this project to openwrt

**Comment by Frans-Willem** [comment]
I'd love to give it a shot, but due to my heavy use of C++ templates, the executable size has grown a bit out of proportion. On normal machines/raspberry pi's that's not that big of a problem, but it might be on OpenWRT :-/

**Comment by utya1988** [comment]
Its a pity

**Comment by Frans-Willem** [comment]
Closing this, as it's not really feasible.

**Comment by itgb** [comment]
we have port it to openwrt , however there is a new issue occurs: it trigger segment fault error. The error.log is following ,pls help.
[err.log](https://github.com/Frans-Willem/AqaraHub/files/4035048/err.log)
