### ISSUE TITLE
Use Hunter package manager

### ISSUE THREAD

**Issue by speqtr** [Frans-Willem/AqaraHub#49]
[Hunter](https://github.com/ruslo/hunter) package manager can be used instead of conan. Hunter is a CMake driven cross-platform package manager for C/C++. And it doesn't require any third-party software for dependency managment (it uses CMake scripts for dependency managment).

This update will simplify the "Getting started" guide for developers, because all dependencies (including Boost libraries) will be installed automatically after opening project in IDE or running cmake from command line.

**Comment by speqtr** [comment]
@Frans-Willem What do yoy think about this proposal? 🙂

**Comment by speqtr** [comment]
If you are interested in merging this kind of changes then I will open a new PR with the two updates:
1. Remove Conan related files;
2. Add Hunter as package manager and install deps (like Boost) using it.

**Comment by Frans-Willem** [comment]
Sounds good! Just make sure that you can still build without Hunter too :)

**Comment by Frans-Willem** [comment]
Seeing as it was almost a year since the last comment, I'm closing this issue for now.
This does not mean I won't permit a pull request adding in Hunter support, I'm just cleaning up the list of issues.
