### ISSUE TITLE
[Feature] Ability to send commands from MQTT

### ISSUE THREAD

**Issue by Frans-Willem** [Frans-Willem/AqaraHub#8]
Turning on/off the Xiaomi Smart Plug [ZNCZ02LM](http://www.giga-tel.com/obrwm/024/th-i024270-xiaomi-wifi-zasuvka-_58ec73cfe286c.jpg) requires sending commands, e.g. to cluster 0x0006, endpoint 0x01, command 0x00 (off), 0x01 (on), or 0x02 (toggle).

Some commands require a payload, so a possible solution would be to send
[] to root/command/158D00015D231D/1/OnOff/On
(extended id, endpoint, cluster, command).

Payload could be implemented by giving a list of JSON-encoded ZclVariants, possibly dropping the header...

**Comment by Frans-Willem** [comment]
Code to send commands is rather trivial, but we need a way to keep track of which transaction number we send to each node. Will probably add SQLite as a dependency at some point.

**Comment by Frans-Willem** [comment]
Update on this: SQLite appears to not be needed, I made a mistake while testing if a sensor actually checked the transaction sequence number: apparently it doesn't check it at all.
I've just commited some new methods in ZclEndpoint for this that have been tested, next up is wiring this up to MQTT.

**Comment by Frans-Willem** [comment]
I've just checked in code for this. Doesn't support payloads yet, but good enough for On/Off/Toggle on the Xiaomi Smart Plug.
Example:
```
mosquitto_pub -h ArchServer -t AqaraHub/command/158D00015D231D/1/OnOff/Toggle -m test
```

**Comment by Gabor9** [comment]
Cannot get it working.
I try this:

`mosquitto_pub  -h 192.168.1.126 -t AqaraHub/command/158D0001DC9587/1/OnOff/Toggle -m test`

In: "$ mosquitto_sub  -d -t AqaraHub/#"  client panel  I receive this:

```
Client mosqsub/1229-eRaspberry received PUBLISH (d0, q0, r0, m0, 'AqaraHub/command/158D0001DC9587/1/OnOff/Toggle', ... (4 bytes))
test
```

But nothing changes in AqaraHub panel and on the device. Any idea?

**Comment by Frans-Willem** [comment]
Are you getting any debug output in the AqaraHub console ?

**Comment by Gabor9** [comment]
No output.  
I tried to slightly change the topic string at the end to see if I mistyped it but it says the topic not handled. But it is silent for the above (correct) topic.

**Comment by Gabor9** [comment]
Any chance I can provide more debug or log info? Just let me know..

**Comment by Frans-Willem** [comment]
Yes, can you try compiling the recent commit (https://github.com/Frans-Willem/AqaraHub/commit/501c6dc6ec59bb40d2a7976a2d1089860190d815), and give me the debug output when trying to send a command? And can you try with other commands too ('On', 'Off') ?
I have a feeling 'Toggle' isn't quite working on the Smart Plug...

**Comment by Gabor9** [comment]
Got the same results as before.
If I publish anything to topic `AqaraHub/command/158D0001DC9587/1/OnOff/Toggle` the console  is silent.  It seems to listening to this topic only, as I change the topic I receive: 
`<DEBG> [OnPublish] Unhandled MQTT publish to command/158D0001DC9587/1/OnOff`

While I was fiddling with zigbee-shepherd I was able to toggle this switch via this JS test code:

```
client.on('message', function (topic, message) {
    var ep = shepherd.find('0x00158d0001dc9587', 1);    // returns undefined if not found
    // use functional command to operate a remote endpoint
    ep.functional('genOnOff', 'toggle', {}, function (err, rsp) {
          if (!err)
               console.log('<RSP>:' + rsp); // { cmdId: 2, statusCode: 0 }
            });
})
```

**Comment by Frans-Willem** [comment]
Are you absolutely sure you recompiled with my latest changes?
Whenever I send the same string as you do, it will attempt to send :/

**Comment by Gabor9** [comment]
Yes, it was logged like this : Updating c242c7f..501c6dc

**Comment by Frans-Willem** [comment]
Should be fixed on 32-bit machines (like Raspberry Pi's) too since https://github.com/Frans-Willem/AqaraHub/commit/274c1e26c7785d38cba679013617ae1da708e714
